config/routes.rb
Rails.application.routes.draw do
  resources :shoppings
  resources :rooms
  resources :products
  resources :kinds
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
root "products#index"
end

app/models/kind.rb
class Kind < ApplicationRecord
    def to_s
        name
    end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: %i[ show edit update destroy ]

  # GET /kinds or /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1 or /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds or /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: "Kind was successfully created." }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1 or /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: "Kind was successfully updated." }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1 or /kinds/1.json
  def destroy
    @kind.destroy!

    respond_to do |format|
      format.html { redirect_to kinds_path, status: :see_other, notice: "Kind was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def kind_params
      params.expect(kind: [ :name ])
    end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/kinds/_form.html.erb
<%= form_with(model: kind) do |form| %>
  <% if kind.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
        <% kind.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kinds/_kind.html.erb
<div id="<%= dom_id kind %>">
  <p>
    <strong>Name:</strong>
    <%= kind.name %>
  </p>

</div>

app/views/kinds/edit.html.erb
<% content_for :title, "Editing kind" %>

<h1>Editing kind</h1>

<%= render "form", kind: @kind %>

<br>

<div>
  <%= link_to "Show this kind", @kind %> |
  <%= link_to "Back to kinds", kinds_path %>
</div>

app/views/kinds/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Kinds" %>

<h1>Kinds</h1>

<div id="kinds">
  <% @kinds.each do |kind| %>
    <%= render kind %>
    <p>
      <%= link_to "Show this kind", kind %>
    </p>
  <% end %>
</div>

<%= link_to "New kind", new_kind_path %>

app/views/kinds/new.html.erb
<% content_for :title, "New kind" %>

<h1>New kind</h1>

<%= render "form", kind: @kind %>

<br>

<div>
  <%= link_to "Back to kinds", kinds_path %>
</div>

app/views/kinds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kind %>

<div>
  <%= link_to "Edit this kind", edit_kind_path(@kind) %> |
  <%= link_to "Back to kinds", kinds_path %>

  <%= button_to "Destroy this kind", @kind, method: :delete %>
</div>