config/routes.rb
Rails.application.routes.draw do
  resources :shoppings
  resources :rooms
  resources :products
  resources :kinds
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :kind, optional: true
  
  validates :name, :kind, :stock, :image, :price, presence: true

  def to_s
    name
  end

  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]


# GET /products or /products.json
def index
  @products = Product.order(:id) 
end


  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.expect(product: [ :name, :kind_id, :stock, :image, :price ])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.association :kind, required: true  %>
    <%= f.input :stock, required: true %>
    <%= f.input :image, required: true %>
    <%= f.input :price, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="text-center mt-4" id="<%= dom_id product %>">
  <p>
    <strong>Nom :</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Type :</strong>
    <%= link_to product.kind %>
  </p>

  <p>
    <strong>Stock :</strong>
    <%= product.stock %>
  </p>

  <p>
    <strong> </strong>
    <%= image_tag product.image %>
  </p>

  <p>
    <strong>Prix :</strong>
    <%= product.price %>
  </p>

</div>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Products" %>

<div id="products" class="container text-center">
  <h1 class="my-4">Marco Distrib</h1>
  
  <div class="d-flex justify-content-center align-items-center gap-2 m-4">
    <%= link_to "Ajouter un produit", new_product_path, class: "btn btn-success" %>
    <%= link_to "Voir les commandes", shoppings_path, class: "btn btn-warning" %>
  </div>
</div>




<div class="container bg-black p-2">
  <div id="products" class="container bg-dark p-1">
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-lg-4">
          <div class="card m-2">
            <% if product.stock > 0 %>
              <%= link_to "/shoppings/new?product_id=#{product.id}", class: "product-link" do %>
                <div class="ratio ratio-1x1">
                  <%= image_tag(product.image, class: "card-img-top object-fit-cover image") %>
                </div>
              <% end %>
            <% else %>
            <div class="ratio ratio-1x1">
              <img src="<%= product.image %>" class="card-img-top object-fit-cover">
              </div>
            <% end %>
            <p> Produit : <%= product.name %> </p>
            <p><%= if product.stock > 0
            "Stock : #{product.stock} restants"
            else
            "Rupture de stock" 
            end %></p>
            <p> Prix : <%= product.price %> € </p>

            <p>
              <%= link_to "Show this product", product %>
              
            </p>
          </div>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>
<div class="text-center m-4">
<%= link_to "Commander", new_shopping_path, class: "btn btn-success fixed-bottom" %>
</div>

app/views/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div class="container">


  <div class="text-center m-4">
  <%= link_to "Edit this product", edit_product_path(@product), class: "btn btn-success" %>
  </div>

  <div class="text-center m-4">
  <%= link_to "Back to products", products_path, class: "btn btn-warning" %>
  </div>

  <div class="text-center m-4">
  <%= button_to "Destroy this product", @product, method: :delete, class: "btn btn-danger" %>
  </div>



</div>